services:
  songs:
    image: php:8.2-apache
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.songs.entrypoints=web,websecure"
      - "traefik.http.routers.songs.rule=Host(`songs.magnusso.nz`)"
      - "traefik.http.routers.songs.tls.certresolver=myresolver"
      - "traefik.http.services.songs.loadbalancer.server.port=80"
    expose:
      - 80
    volumes:
      - /home/jannes/vps/songs/dist/browser:/var/www/html
    networks:
      - traefik

networks:
  traefik:
    external: true
